### ISSUE TITLE
[Tracker] Transition to "Marketplace"

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/marketplace-site#67]
Ok, I think the decision was already made mooooonths ago, so this is not an RFC but a tracker. 

We already renamed this and related repositories, got the new wording on a few pages in the docs and use the "Marketplace" term day in and out, but we didn't actually made the real transition.

This are the steps that should be done in order to properly transition:
- [x] Put `extensions.bolt.cm` on `market.bolt.cm`
- [x] Make 301 redirects from `extensions.bolt.cm` to `market.bolt.cm` for backlinks and Bolt backend BC
- [x] Change heading on the marketplace application and look for other text sections to change
- [x] Check documentation for text sections and links to change 
- [x] Change links on bolt.cm
- [x] Adjust bolt/bolt to point to the new URL for extension handling (3.2/3.3) (even if we have the redirect)
- [x] Moving the Disqus set up (Disqus was removed in PR bolt/marketplace-theme/pull/6)

That are the ones that pop up in my head, if you have additional tasks, feel free to add them.

**Comment by SahAssar** [comment]
Do we have any extensions where the disqus comments are actually used? The only one among the six most used extensions that has even single comment is menueditor.

Wouldn't it be better to allow the extension author to link to a dedicated thread on discuss.bolt.cm if they want to have a comment thread about the extension?

**Comment by PhillippOhlandt** [comment]
@SahAssar Not sure if you read it on Slack, but I already told @GawainLynch that I am for :fire: Disqus on the store. He would be fine with it too. He only added the task here so it is complete.

**Comment by SahAssar** [comment]
Ah, gotcha. In that case my vote is also for 🔥 . It loads ~200kb of js/css to display a comment section that is basically always empty and that no one seems to use.

**Comment by PhillippOhlandt** [comment]
@SahAssar If you want to do another PR today (hacktoberfest :)), feel free to remove Disqus. I will merge it in then.

**Comment by bobdenotter** [comment]
Another consideration is that people don't really "get" the comment section. In the few cases it's used, people are using it to ask support questions for the extension. And that's not what it's for. :-)

**Comment by GawainLynch** [comment]
Should be all done now
